name: CI

on:
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: List current directory
        run: ls
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.8'
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
         aws-region: us-east-1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      - name: flake8
        run: flake8 transformar_html.py descarga_html.py
      - name: pytest
        run: pytest test.py
      - name: Deploy with Zappa
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install zappa
          zappa update dev_descarga
          zappa update dev_transform
